// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v6.30.2
// source: product.proto

/* eslint-disable */

export const protobufPackage = "product";

export interface ProductCreateRequest {
  readonly title: string;
  readonly quantity: number;
}

export interface ProductCreateResponse {
  readonly isCreated: boolean;
}

export interface ProductsService {
  Create(request: ProductCreateRequest): Promise<ProductCreateResponse>;
}
