// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v6.30.2
// source: user.proto

/* eslint-disable */

export const protobufPackage = "user";

/** hero/hero.proto */

export interface UserCreateResponse {
  readonly isCreated: boolean;
}

export interface UserCreateRequest {
  readonly firstName: string;
  readonly lastName: string;
  readonly email: string;
}

export interface UsersService {
  Create(request: UserCreateRequest): Promise<UserCreateResponse>;
}
